=== XML-TIM4/ScientificPublications/Backend/data/schemas/Notification.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="https://github.com/XML-TIM4/ScientificPublications"
    xmlns="https://github.com/XML-TIM4/ScientificPublications">
    <xs:element name="notification" type="TNotification"/>
    <xs:complexType name="TNotification">
        <xs:sequence>
            <xs:element name="notification-metadata" type="TNotificationMetadata"/>
            <xs:element name="content" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TNotificationMetadata">
        <xs:sequence>
            <xs:element name="recipient-email" type="xs:string"> </xs:element>
            <xs:element name="recipient-name" type="xs:string"/>
            <xs:element name="date" type="xs:string"> </xs:element>
            <xs:element name="document-id" type="xs:string"/>
            <xs:element name="document-collection" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== XML-TIM4/ScientificPublications/Backend/data/notification-template/EmptyNotification.xml
<?xml version="1.0" encoding="UTF-8"?>
<notification xmlns="https://github.com/XML-TIM4/ScientificPublications"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://github.com/XML-TIM4/ScientificPublications file:/D:/ScientificPublications/Backend/data/schemas/Notification.xsd">
    <notification-metadata>
        <recipient-email/>
        <recipient-name/>
        <date/>
        <document-id/>
        <document-collection/>
    </notification-metadata>
    <content/>
</notification>
