=== XML-TIM4/ScientificPublications/Backend/data/schemas/Review.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="https://github.com/XML-TIM4/ScientificPublications"
    xmlns="https://github.com/XML-TIM4/ScientificPublications">
    <xs:include schemaLocation="ScientificPaper.xsd"/>
    <xs:complexType name="TQuestion">
        <xs:sequence>
            <xs:element name="question-text" type="xs:string"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="answer">
                <xs:complexType mixed="true">
                    <xs:attribute name="selected" type="xs:boolean"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="type">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="text"/>
                    <xs:enumeration value="multiple-choice"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:element name="review" type="TReview"/>
    <xs:complexType name="TReview">
        <xs:sequence>
            <xs:element name="review-metadata" type="TReviewMetadata"/>
            <xs:element name="questionnaire">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="1" name="question"
                            type="TQuestion"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="author-comments">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" name="author-comment" type="TComment"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="editor-comments">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" name="editor-comment" type="TComment"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute default="en" name="language" type="xs:language"/>
        <xs:attribute name="id" type="xs:string"/>
        <xs:anyAttribute processContents="lax"/>
    </xs:complexType>
    <xs:complexType name="TReviewMetadata">
        <xs:sequence>
            <xs:element name="reviewer">
                <xs:complexType>
                    <xs:complexContent>
                        <xs:extension base="TAuthor">
                            <xs:anyAttribute processContents="lax"/>
                        </xs:extension>
                    </xs:complexContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="date">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:date">
                            <xs:anyAttribute processContents="lax"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="recommendation">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:anyAttribute processContents="lax"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="scientific-paper-id">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:anyAttribute processContents="lax"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TComment">
        <xs:sequence>
            <xs:element name="review-reference" type="xs:string" nillable="false"/>
            <xs:element name="comment-text">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="300"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== XML-TIM4/ScientificPublications/Backend/data/document-examples/ReviewInstance.xml
<?xml version="1.0" encoding="UTF-8"?>
<review xmlns="https://github.com/XML-TIM4/ScientificPublications"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="https://github.com/XML-TIM4/ScientificPublications file:/data/schemas/Review.xsd">
    <review-metadata>
        <date>2006-05-04</date>
        <recommendation>accept</recommendation>
        <scientific-paper-id>asdfqwer</scientific-paper-id>
    </review-metadata>
    <questionnaire>
        <question>
            <question-text>question-text0</question-text>
            <answer selected="false">q1a1</answer>
            <answer selected="false">q1a2</answer>
        </question>
        <question>
            <question-text>question-text1</question-text>
            <answer selected="false">q1a1</answer>
            <answer selected="false">q1a2</answer>
            <answer selected="false">q1a3</answer>
        </question>
    </questionnaire>
    <reviewer-comments>
    </reviewer-comments>
    <editor-comments>
        <editor-comment>
            <review-reference>review-reference2</review-reference>
            <comment-text>comment-text2</comment-text>
        </editor-comment>
        <editor-comment>
            <review-reference>review-reference3</review-reference>
            <comment-text>comment-text3</comment-text>
        </editor-comment>
    </editor-comments>
</review>
