=== XML-TIM4/ScientificPublications/Backend/data/schemas/ScientificPaper.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="https://github.com/XML-TIM4/ScientificPublications"
    xmlns="https://github.com/XML-TIM4/ScientificPublications">
    <xs:element name="scientific-paper" type="TScientificPaper"/>
    <xs:complexType name="TScientificPaper">
        <xs:sequence>
            <xs:element name="metadata" type="TMetadata"/>
            <xs:element name="title">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="100"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="authors">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="1" name="author" type="TAuthor"
                        />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="abstract" type="TAbstract"/>
            <xs:element name="content">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="section" type="TSection" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="references">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="reference" type="TReference" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute default="en" name="language" type="xs:language"/>
        <xs:attribute ref="id"/>
    </xs:complexType>
    <xs:complexType name="TAuthor">
        <xs:sequence>
            <xs:element name="name" type="TName"/>
            <xs:element name="email">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[^@]+@[^\.]+\..+"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="affiliation" type="TAffiliation"/>
        </xs:sequence>
        <xs:attribute ref="id"/>
    </xs:complexType>
    <xs:complexType name="TMetadata">
        <xs:sequence>
            <xs:element name="received" nillable="false" type="xs:date"/>
            <xs:element name="revised" nillable="true" type="xs:date"/>
            <xs:element name="accepted" nillable="true" type="xs:date"/>
            <xs:element default="1.0" name="version">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[1-9]\d*.\d{1,2}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="status">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="accepted"/>
                        <xs:enumeration value="rejected"/>
                        <xs:enumeration value="revision"/>
                        <xs:enumeration value="withdrawn"/>
                        <xs:enumeration value="uploaded"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element default="research-paper" name="category">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="research-paper"/>
                        <xs:enumeration value="viewpoint"/>
                        <xs:enumeration value="technical-paper"/>
                        <xs:enumeration value="conceptual-paper"/>
                        <xs:enumeration value="case-study"/>
                        <xs:enumeration value="literature-review"/>
                        <xs:enumeration value="general-review"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="keywords">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="keyword" maxOccurs="unbounded" minOccurs="1">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:minLength value="1"/>
                                    <xs:maxLength value="50"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TName">
        <xs:sequence>
            <xs:element name="first-name">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="middle-name">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="last-name">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TAffiliation">
        <xs:sequence>
            <xs:element name="university">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="city">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="state">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="country">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TAbstract">
        <xs:sequence>
            <xs:element name="abstract-item" type="TAbstractItem" maxOccurs="7" minOccurs="4"/>
        </xs:sequence>
        <xs:attribute ref="id"/>
    </xs:complexType>
    <xs:complexType name="TAbstractItem">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="title">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="purpose"/>
                            <xs:enumeration value="methodology"/>
                            <xs:enumeration value="findings"/>
                            <xs:enumeration value="implications"/>
                            <xs:enumeration value="practical-implications"/>
                            <xs:enumeration value="social-implications"/>
                            <xs:enumeration value="originality"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="TSection">
        <xs:sequence>
            <xs:element name="title" nillable="false">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="paragraph" type="TParagraph" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute ref="id"/>
    </xs:complexType>
    <xs:complexType mixed="true" name="TParagraph">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="figure" type="TFigure"/>
            <xs:element name="table" type="TTable"/>
            <xs:element name="list" type="TList"/>
            <xs:element name="decorator" type="TDecorator"/>
            <xs:element name="quote" type="TQuote"/>
        </xs:choice>
        <xs:attribute ref="id"/>
    </xs:complexType>
    <xs:complexType mixed="true" name="TFigure">
        <xs:sequence>
            <xs:element name="image" type="xs:base64Binary" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="type">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="figure"/>
                    <xs:enumeration value="box"/>
                    <xs:enumeration value="equation"/>
                    <xs:enumeration value="chart"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute ref="id"/>
    </xs:complexType>
    <xs:complexType name="TTable">
        <xs:sequence>
            <xs:element name="header">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="row" type="TRow" maxOccurs="unbounded" minOccurs="0"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="body">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="row" type="TRow" maxOccurs="unbounded" minOccurs="0"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="title">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:minLength value="1"/>
                    <xs:maxLength value="50"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute ref="id"/>
    </xs:complexType>
    <xs:complexType name="TRow">
        <xs:sequence>
            <xs:element name="column" type="TColumn" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="TColumn">
        <xs:restriction base="xs:string">
            <xs:minLength value="0"/>
            <xs:maxLength value="50"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="TList">
        <xs:sequence>
            <xs:element name="list-item" maxOccurs="unbounded" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="0"/>
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute default="false" name="ordered" type="xs:boolean"/>
    </xs:complexType>
    <xs:complexType mixed="true" name="TDecorator">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="bold" type="TDecorator"/>
            <xs:element name="italic" type="TDecorator"/>
            <xs:element name="underline" type="TDecorator"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType mixed="true" name="TQuote">
        <xs:sequence>
            <xs:element name="quote-text">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="30"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="publication" type="TPublication"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TReference">
        <xs:sequence>
            <xs:element name="authors">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="name" type="TName" maxOccurs="unbounded" minOccurs="1"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="publication" type="TPublication"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPublication">
        <xs:sequence>
            <xs:element name="title">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="100"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element minOccurs="0" name="year">
                <xs:simpleType>
                    <xs:restriction base="xs:positiveInteger">
                        <xs:maxInclusive value="2019"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="publisher">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="100"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="place">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:attribute name="id">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="0"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
</xs:schema>

=== XML-TIM4/ScientificPublications/Backend/data/document-examples/ScientificPaperInstance.xml
<?xml version="1.0" encoding="UTF-8"?>
<scientific-paper xmlns="https://github.com/XML-TIM4/ScientificPublications"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="https://github.com/XML-TIM4/ScientificPublications file:/D:/ScientificPublications/XMLSchemas/ScientificPaper.xsd" language="en" id="">
    <metadata>
        <received>2021-06-14Z</received>
        <revised>2020-03-10Z</revised>
        <accepted>2020-08-05Z</accepted>
        <version>1.0</version>
        <status>uploaded</status>
        <category>research-paper</category>
        <keywords>
            <keyword>gBjYErt7SbwGkjQMPiRQ-eno12</keyword>
            <keyword>v</keyword>
        </keywords>
    </metadata>
    <title>gYz5LPRg.fDxCPZvDkm-eYFs2E_8bq3Vs7bW86-y_di4HFr_kZsuq5Bi-xK_I7iet3d3FoTP_7</title>
    <authors>
        <author id="">
            <name>
                <first-name>M.mJ8Lv5aq0irnN</first-name>
                <middle-name>szOpWlVonEfoMVPOof2xmC3jLM7y6Gw9HH7xQix7j</middle-name>
                <middle-name>bFWzi3Ntu_fm</middle-name>
                <last-name>cotQFAjOAr</last-name>
            </name>
            <email>%$ª@'.r</email>
            <affiliation>
                <university>RC8sI0Cxeb3QDv8W8_XbAJBk7rSQNGE-jd.agH6</university>
                <city>wA1qOUBSyN3HVPXOTNfue0</city>
                <state>oRqL7SdkVvCIz</state>
                <country>e8WXZAyJ9EdGdfiC6.TJ0-ehZZFHeXIN1O4UpGHnh</country>
            </affiliation>
        </author>
        <author id="">
            <name>
                <first-name>lVnDrjmD</first-name>
                <middle-name>sMbuT-zCtFWlSfHUqWa</middle-name>
                <middle-name>SckRDtWrxowu_0CDFY</middle-name>
                <last-name>b1fui-V.3LFgX057iSNzZ-CFt.yJH_P4WPwgqq2qQqV</last-name>
            </name>
            <email>5@K.h</email>
            <affiliation>
                <university>R9b-jMjLmU_NeKYAJ-zFi3FBdMOJC3</university>
                <city>osLL</city>
                <state>uZTuR-Xx1</state>
                <country>UHQTy7mCkrhtR0WpToWiu6rKHKN6</country>
            </affiliation>
        </author>
    </authors>
    <abstract id="">
        <abstract-item title="Purpose">CzD33J1hPViTWPAqYW82p-mBf</abstract-item>
        <abstract-item title="Findings">DaNoaYAMSz7rH</abstract-item>
        <abstract-item title="Social Implications">y</abstract-item>
        <abstract-item title="Implications">ELyou3bBqFqWnzzm</abstract-item>
    </abstract>
    <content>
        <section id="/oi">
            <title>vCdQ3R2EkpFISjVd1</title>
            <paragraph id=" #~">
                <figure type="equation" id="">
                    <image>6985777971898673857571808767746668867878806778797183888389888981857587838588708969737480876985668870866987907586</image>
                    <image>6687816581807875</image>
                </figure>
                <quote>
                    <quote-text>T1KADIxas5jp0cC395gtLJR2izQQ8</quote-text>
                    <publication>
                        <title>yZ7DDR</title>
                        <publisher>j62Ajr2pK46f0ZKXw</publisher>
                        <place>Q2uQwWl_O9Rv</place>
                    </publication>
                </quote>
            </paragraph>
            <paragraph id="">
                <table title="m44MpL" id="Q+://=">
                    <header>
                    </header>
                    <body>
                    </body>
                </table>
                <quote>
                    <quote-text>ZlN12f0as9TQI1rqgOvZA</quote-text>
                    <publication>
                        <title>NhL4K8a</title>
                        <publisher>P7AKE4rofSGKjbS.2LGPsrwQSh.E-150laxyri_7dIiTCBt3c4mT6dMDCLYYv6vE</publisher>
                        <place>Vdij5WAXb82_.0TOKHTOQXxde8VHsJyccT</place>
                    </publication>
                </quote>
            </paragraph>
        </section>
        <section id="">
            <title>iVjS</title>
            <paragraph id="">
                <table title="S" id="">
                    <header>
                    </header>
                    <body>
                    </body>
                </table>
                <decorator>
                    <italic>
                        <underline>
                            <bold>
                            </bold>
                            <bold>
                            </bold>
                        </underline>
                        <bold>
                            <underline>
                            </underline>
                            <underline>
                            </underline>
                        </bold>
                    </italic>
                    <italic>
                        <underline>
                            <bold>
                            </bold>
                            <bold>
                            </bold>
                        </underline>
                        <bold>
                            <underline>
                            </underline>
                            <underline>
                            </underline>
                        </bold>
                    </italic>
                </decorator>
            </paragraph>
            <paragraph id="P:/\!q. #~">
                <figure type="figure" id="">
                    <image>7088887067698968</image>
                    <image>728186726674707089828986718972868273708078717970737089888390888568867986778767748167658775686582738285777279677169857286</image>
                </figure>
                <figure type="equation" id="">
                    <image>77836766758366718187906780698168</image>
                    <image>ZGVmYXVsdA==</image>
                </figure>
            </paragraph>
        </section>
    </content>
    <references>
        <reference>
            <authors>
                <name>
                    <first-name>RMgd</first-name>
                    <middle-name>OisVa36t5HxURaDudf</middle-name>
                    <middle-name>jUWyIS</middle-name>
                    <last-name>uAhinIkiMr9qh.De-p3CSOcl6OLAqH</last-name>
                </name>
                <name>
                    <first-name>Pb4AF01b</first-name>
                    <middle-name>Hs4PINfY6heUo_66iUrMH086HG.9GjOpYUoRU</middle-name>
                    <middle-name>_TtzY0MN1UZY-FnMk-3xUhaX_qzrGXK9BunljStLooD</middle-name>
                    <last-name>dqZHONv8BJc2rCqofS2x5V6iu-lBwVSKXb9kFgO_1mZ5</last-name>
                </name>
            </authors>
            <publication>
                <title>x3pVcSDs7QjpKc7u591cS9l3vwoaJJwpQvL_SLSQ0MNq9LZXb3B88lcG.YdAEWQjyz0IiaRtXTR94sqAua1xG</title>
                <year>370</year>
                <publisher>eZ</publisher>
                <place>ESgXEgzhhYijceLZB-PVoNbiCci7OkvWo4P24G2q_</place>
            </publication>
        </reference>
        <reference>
            <authors>
                <name>
                    <first-name>FPNtjC.ZmlWmiQXxJTwsR</first-name>
                    <middle-name>j_3</middle-name>
                    <middle-name>Npu67NPio-wNqb2d1Oblms7</middle-name>
                    <last-name>P5-rGxHFWWhsn</last-name>
                </name>
                <name>
                    <first-name>hm2oBm_P</first-name>
                    <middle-name>TfdzwMe5B</middle-name>
                    <middle-name>tqISBd1tj</middle-name>
                    <last-name>xrkSrRX1p3GKWgQDUvsnd_C9z</last-name>
                </name>
            </authors>
            <publication>
                <title>odHc9k8015Lrxn</title>
                <year>327</year>
                <publisher>Jw8ZRAwULwiN1ADe10rHonk7OJSAZrQ0_C4_jj.if2i-ogKH</publisher>
                <place>MidzhbfBlrLqsbiX7UcOl6CjQZxH667en</place>
            </publication>
        </reference>
    </references>
</scientific-paper>
