=== XML-TIM4/ScientificPublications/Backend/data/schemas/ScientificPaper.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="https://github.com/XML-TIM4/ScientificPublications"
    xmlns="https://github.com/XML-TIM4/ScientificPublications">
    <xs:element name="scientific-paper" type="TScientificPaper"/>
    <xs:complexType name="TScientificPaper">
        <xs:sequence>
            <xs:element name="metadata" type="TMetadata"/>
            <xs:element name="title">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="100"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="authors">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="1" name="author" type="TAuthor"
                        />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="abstract" type="TAbstract"/>
            <xs:element name="content">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="section" type="TSection" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="references">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="reference" type="TReference" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute default="en" name="language" type="xs:language"/>
        <xs:attribute ref="id"/>
    </xs:complexType>
    <xs:complexType name="TAuthor">
        <xs:sequence>
            <xs:element name="name" type="TName"/>
            <xs:element name="email">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[^@]+@[^\.]+\..+"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="affiliation" type="TAffiliation"/>
        </xs:sequence>
        <xs:attribute ref="id"/>
    </xs:complexType>
    <xs:complexType name="TMetadata">
        <xs:sequence>
            <xs:element name="received" nillable="false" type="xs:date"/>
            <xs:element name="revised" nillable="true" type="xs:date"/>
            <xs:element name="accepted" nillable="true" type="xs:date"/>
            <xs:element default="1.0" name="version">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[1-9]\d*.\d{1,2}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="status">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="accepted"/>
                        <xs:enumeration value="rejected"/>
                        <xs:enumeration value="revision"/>
                        <xs:enumeration value="withdrawn"/>
                        <xs:enumeration value="uploaded"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element default="research-paper" name="category">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="research-paper"/>
                        <xs:enumeration value="viewpoint"/>
                        <xs:enumeration value="technical-paper"/>
                        <xs:enumeration value="conceptual-paper"/>
                        <xs:enumeration value="case-study"/>
                        <xs:enumeration value="literature-review"/>
                        <xs:enumeration value="general-review"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="keywords">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="keyword" maxOccurs="unbounded" minOccurs="1">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:minLength value="1"/>
                                    <xs:maxLength value="50"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TName">
        <xs:sequence>
            <xs:element name="first-name">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="middle-name">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="last-name">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TAffiliation">
        <xs:sequence>
            <xs:element name="university">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="city">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="state">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="country">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TAbstract">
        <xs:sequence>
            <xs:element name="abstract-item" type="TAbstractItem" maxOccurs="7" minOccurs="4"/>
        </xs:sequence>
        <xs:attribute ref="id"/>
    </xs:complexType>
    <xs:complexType name="TAbstractItem">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="title">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="purpose"/>
                            <xs:enumeration value="methodology"/>
                            <xs:enumeration value="findings"/>
                            <xs:enumeration value="implications"/>
                            <xs:enumeration value="practical-implications"/>
                            <xs:enumeration value="social-implications"/>
                            <xs:enumeration value="originality"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="TSection">
        <xs:sequence>
            <xs:element name="title" nillable="false">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="paragraph" type="TParagraph" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute ref="id"/>
    </xs:complexType>
    <xs:complexType mixed="true" name="TParagraph">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="figure" type="TFigure"/>
            <xs:element name="table" type="TTable"/>
            <xs:element name="list" type="TList"/>
            <xs:element name="decorator" type="TDecorator"/>
            <xs:element name="quote" type="TQuote"/>
        </xs:choice>
        <xs:attribute ref="id"/>
    </xs:complexType>
    <xs:complexType mixed="true" name="TFigure">
        <xs:sequence>
            <xs:element name="image" type="xs:base64Binary" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="type">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="figure"/>
                    <xs:enumeration value="box"/>
                    <xs:enumeration value="equation"/>
                    <xs:enumeration value="chart"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute ref="id"/>
    </xs:complexType>
    <xs:complexType name="TTable">
        <xs:sequence>
            <xs:element name="header">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="row" type="TRow" maxOccurs="unbounded" minOccurs="0"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="body">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="row" type="TRow" maxOccurs="unbounded" minOccurs="0"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="title">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:minLength value="1"/>
                    <xs:maxLength value="50"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute ref="id"/>
    </xs:complexType>
    <xs:complexType name="TRow">
        <xs:sequence>
            <xs:element name="column" type="TColumn" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="TColumn">
        <xs:restriction base="xs:string">
            <xs:minLength value="0"/>
            <xs:maxLength value="50"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="TList">
        <xs:sequence>
            <xs:element name="list-item" maxOccurs="unbounded" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="0"/>
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute default="false" name="ordered" type="xs:boolean"/>
    </xs:complexType>
    <xs:complexType mixed="true" name="TDecorator">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="bold" type="TDecorator"/>
            <xs:element name="italic" type="TDecorator"/>
            <xs:element name="underline" type="TDecorator"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType mixed="true" name="TQuote">
        <xs:sequence>
            <xs:element name="quote-text">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="30"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="publication" type="TPublication"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TReference">
        <xs:sequence>
            <xs:element name="authors">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="name" type="TName" maxOccurs="unbounded" minOccurs="1"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="publication" type="TPublication"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPublication">
        <xs:sequence>
            <xs:element name="title">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="100"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element minOccurs="0" name="year">
                <xs:simpleType>
                    <xs:restriction base="xs:positiveInteger">
                        <xs:maxInclusive value="2019"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="publisher">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="100"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="place">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:attribute name="id">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="0"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
</xs:schema>

=== XML-TIM4/ScientificPublications/Backend/data/schemas/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<scientific-paper xmlns="https://github.com/XML-TIM4/ScientificPublications"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="https://github.com/XML-TIM4/ScientificPublications file:/D:/ScientificPublications/Backend/data/schemas/ScientificPaper.xsd" language="en" id="IA1yj">
    <metadata>
        <received>2022-05-06</received>
        <revised>2020-09-19</revised>
        <accepted>2021-10-14Z</accepted>
        <version>1.0</version>
        <status>withdrawn</status>
        <category>research-paper</category>
        <keywords>
            <keyword>cDMge0W6HPX1-ik9KtW-2NBDjq5qUfFs3_</keyword>
            <keyword>YM5r512XMizQaWyxh5q5INWvmDDrAaOc0YtlcKtIVsBSK1mc1u</keyword>
        </keywords>
    </metadata>
    <title>CP41A-w1wj3D</title>
    <authors>
        <author id="rX9YzugJ">
            <name>
                <first-name>_keo</first-name>
                <middle-name>qf1rb0X15poxgWZNVf6TL4I4Twb6QEnrAw9d</middle-name>
                <middle-name>UeH0LN</middle-name>
                <last-name>W2meXDmksv54Lm5MRjQWsBrrWwSl8</last-name>
            </name>
            <email>Ú@~V +.ara</email>
            <affiliation>
                <university>PEz4z1k1mqty1DlsN_mukgbeD.hH8W</university>
                <city>FZxUfl</city>
                <state>ga</state>
                <country>aQDzjU_jfwDJ-W</country>
            </affiliation>
        </author>
        <author id="mDYGu4cQyGUin9Am5ARBT">
            <name>
                <first-name>lj-PJzwK..ZKJs74_lPUedhGuO03byrMOM9EvuoLavff4hO</first-name>
                <middle-name>p9mLAoGexgLGm17EM</middle-name>
                <middle-name>f8HY.UlL-MU.6qH_UT8</middle-name>
                <last-name>v-r1kbDQU0OJ-ycZ4Ym8wKVi_X-m02eC4C</last-name>
            </name>
            <email>í0;@g.ofn</email>
            <affiliation>
                <university>wsVZ9.okE</university>
                <city>CF6nImGXlZpWu.4so8gV0i</city>
                <state>C6KlrTcyaPWY2h7qtYEW.B0GG5Ma5EQZSRl</state>
                <country>v-5fJNN8OtjrkCxpudmCZyGNGny3Z4F84</country>
            </affiliation>
        </author>
    </authors>
    <abstract id="yDViFVvTbmivtBJEc">
        <abstract-item title="Purpose">oNlxQ6JGRMBLLFHfcPe881va8</abstract-item>
        <abstract-item title="Methodology">YAaU_1-c7W0jrLaxQFOrEUtxev_lK</abstract-item>
        <abstract-item title="Findings">h</abstract-item>
        <abstract-item title="Originality">Xris_W7lp5SPgNXW9</abstract-item>
    </abstract>
    <content>
        <section id="MYGa29VelXSEVFo">
            <title>WKLhqjN5lsr0fFWo</title>
            <paragraph id="rU8EIJiACeWG">
                <decorator>
                    <bold>
                        <italic>
                            <underline>
                            </underline>
                            <underline>
                            </underline>
                        </italic>
                        <italic>
                            <underline>
                            </underline>
                            <underline>
                            </underline>
                        </italic>
                    </bold>
                    <bold>
                        <italic>
                            <underline>
                            </underline>
                            <underline>
                            </underline>
                        </italic>
                        <italic>
                            <underline>
                            </underline>
                            <underline>
                            </underline>
                        </italic>
                    </bold>
                </decorator>
                <list ordered="false">
                    <list-item>kPEYwg2REQ</list-item>
                    <list-item>OdOmcd41Jk4aIyIyHuiwDZFMg</list-item>
                </list>
            </paragraph>
            <paragraph id="pFJ2y0eeL">
                <figure type="equation" id="UEfy2.is0Bnq">
                    <image>677982717677707986667186698088907065828472658871</image>
                    <image>857577897783817880797674658184827087686866837089867674778688898572676767757279868880888789688379</image>
                </figure>
                <figure type="chart" id="Ny79RAeF">
                    <image>87778970737581886776847265716785738688738972668783817086857865708086676673827766778879888469798190676866</image>
                    <image>81796867857868798270706777807683</image>
                </figure>
            </paragraph>
        </section>
        <section id="M5S6.yabP8XZ">
            <title>hN.p_EfqApcG</title>
            <paragraph id="zj9XVSOtsv84mrWi">
                <decorator>
                    <bold>
                        <underline>
                            <italic>
                            </italic>
                            <italic>
                            </italic>
                        </underline>
                        <italic>
                            <underline>
                            </underline>
                            <underline>
                            </underline>
                        </italic>
                    </bold>
                    <underline>
                        <bold>
                            <italic>
                            </italic>
                            <italic>
                            </italic>
                        </bold>
                        <italic>
                            <bold>
                            </bold>
                            <bold>
                            </bold>
                        </italic>
                    </underline>
                </decorator>
                <figure type="equation" id="bQh-VLgwvu8Czp">
                    <image>736570838590857075827968</image>
                    <image>70848381838082658070728581846865888967748887857084668478687890847886818190877487</image>
                </figure>
            </paragraph>
            <paragraph id="ye">
                <decorator>
                    <bold>
                        <underline>
                            <italic>
                            </italic>
                            <italic>
                            </italic>
                        </underline>
                        <italic>
                            <underline>
                            </underline>
                            <underline>
                            </underline>
                        </italic>
                    </bold>
                    <bold>
                        <underline>
                            <italic>
                            </italic>
                            <italic>
                            </italic>
                        </underline>
                        <italic>
                            <underline>
                            </underline>
                            <underline>
                            </underline>
                        </italic>
                    </bold>
                </decorator>
                <list ordered="false">
                    <list-item>RgRknuxqUZIg4cfr4nJRyosuJAGnU</list-item>
                    <list-item>et43hbt_WBlGBToV9p-opsP-LHN.oFs0Lc3ot9nwntq</list-item>
                </list>
            </paragraph>
        </section>
    </content>
    <references>
        <reference>
            <authors>
                <name>
                    <first-name>MyWfrJIUhq.mg1n</first-name>
                    <middle-name>b5ewiYuUszCL3AAZWQCCvy7En</middle-name>
                    <middle-name>nu-YABgogONZE60qMm7OjweMEuCIn</middle-name>
                    <last-name>K_i04tyHlBrCpa31M9p1hDhPsxe9Qpxy-ew_VdjS4Wb</last-name>
                </name>
                <name>
                    <first-name>n0MaxjIH_0ant.YH03ex0GA1VBfY3wfomHy0S</first-name>
                    <middle-name>E0xJmYtGezFejmtq-76bnG0E4L3N3X5jGF0</middle-name>
                    <middle-name>cKvDH5KChXk0AxBJ2a-o</middle-name>
                    <last-name>PrKs1ZFhI4R5AVTNnga6MR5xxSoHYPyCAHqsy</last-name>
                </name>
            </authors>
            <publication>
                <title>B49AC90tkY782g_yRHafFhNoC</title>
                <year>1205</year>
                <publisher>rpqxXXi7uDdka40hnIu4hQ8TdOQdGv5xpttcg6c4zKXESfQpbsp1rXvfBaRlSD2.g9AkT</publisher>
                <place>G</place>
                <url>iEgdJEI_jpBa</url>
            </publication>
        </reference>
        <reference>
            <authors>
                <name>
                    <first-name>kT7Aj</first-name>
                    <middle-name>o</middle-name>
                    <middle-name>RSb.MYTB</middle-name>
                    <last-name>AbLc8lkNM8T9_lAjGEVjP_4evCL.WIfxM7yGf5IGSLG</last-name>
                </name>
                <name>
                    <first-name>Qvl025G-TVRh79j-B2VJzCrRa15jW4V</first-name>
                    <middle-name>Tu21XALCmGUMCvnkumEKZunk</middle-name>
                    <middle-name>IRx7zW_Rn1lI-cFpLA_1H</middle-name>
                    <last-name>bGqUIucpysXo_omKlWf2jFa</last-name>
                </name>
            </authors>
            <publication>
                <title>ucF5CM.IgcMOi0Cuwxcj4yHHWqMCOz</title>
                <year>809</year>
                <publisher>JWAr06ySegAkF</publisher>
                <place>IN3HHcDT7UgZFzax</place>
                <url>EVNQkFpvLwLEL11nPNjGuA6DUIl</url>
            </publication>
        </reference>
    </references>
</scientific-paper>
