=== XML-TIM4/ScientificPublications/Backend/data/schemas/Users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="https://github.com/XML-TIM4/ScientificPublications"
    xmlns="https://github.com/XML-TIM4/ScientificPublications">

    <xs:complexType name="TUser">
        <xs:sequence>
            <xs:element name="username" type="xs:string"/>
            <xs:element name="password">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="^([a-zA-Z0-9@*#]{8,15})$"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="email">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[^@]+@[^\.]+\..+"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="publication-roles">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="0" name="publication-role"
                            type="TPublicationRole"/>
                    </xs:sequence>
                </xs:complexType>
                <xs:unique name="unique-publication-id">
                    <xs:selector xpath="publication-role"></xs:selector>
                    <xs:field xpath="@document-id"></xs:field>
                </xs:unique>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="author-id">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern
                        value="(([a-zA-Z][0-9a-zA-Z+\\-\\.]*:)?/{0,2}[0-9a-zA-Z;/?:@&amp;amp;=+$\\.\\-_!~*'()%]+)?( #[0-9a-zA-Z;/?:@&amp;amp;=+$\\.\\-_!~*'()%]+)?"
                    />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute default="false" name="is-editor" type="xs:boolean"/>
    </xs:complexType>
    <xs:complexType name="TPublicationRole">
        <xs:attribute name="document-id" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern
                        value="(([a-zA-Z][0-9a-zA-Z+\\-\\.]*:)?/{0,2}[0-9a-zA-Z;/?:@&amp;amp;=+$\\.\\-_!~*'()%]+)?( #[0-9a-zA-Z;/?:@&amp;amp;=+$\\.\\-_!~*'()%]+)?"
                    />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="role" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="REVIEWER"/>
                    <xs:enumeration value="AUTHOR"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="user" type="TUser"/>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="unique-username">
            <xs:selector xpath="user/username"/>
            <xs:field xpath="."/>
        </xs:unique>
    </xs:element>
</xs:schema>

=== XML-TIM4/ScientificPublications/Backend/data/document-examples/UsersInstance.xml
<?xml version="1.0" encoding="UTF-8"?>
<users xmlns="https://github.com/XML-TIM4/ScientificPublications"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="https://github.com/XML-TIM4/ScientificPublications file:/D:/ScientificPublications/Backend/data/schemas/Users.xsd">
    <user author-id="" is-editor="false">
        <username>nfq5E8</username>
        <password>^#641U#*HX*i#*3$</password>
        <email>!@#.af</email>
        <publication-roles>
            <publication-role document-id="" role="AUTHOR"/>
            <publication-role document-id="T:/s" role="REVIEWER"/>
        </publication-roles>
    </user>
    <user author-id="" is-editor="false">
        <username>Iu0NJVilkqB6TY9z</username>
        <password>^*GLf#zo**#T#B#b$</password>
        <email>?+¬ù@).ao</email>
        <publication-roles>
            <publication-role document-id=" #&amp;\" role="AUTHOR"/>
            <publication-role document-id="" role="REVIEWER"/>
        </publication-roles>
    </user>
</users>
